spring:
  application:
    name: platform
  datasource:
    url: jdbc:mysql://localhost:3306/trading_platform
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: trading_platform